name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With these settings '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Mister.Version Version
      description: What version of Mister.Version are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET Version
      description: Which .NET version are you using?
      options:
        - .NET 8.0
        - .NET 9.0
        - .NET 10.0
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - Linux
        - macOS
        - Other (please specify in additional context)
    validations:
      required: true

  - type: textarea
    id: repository-structure
    attributes:
      label: Repository Structure
      description: Describe your repository structure (monorepo, single project, etc.)
      placeholder: |
        Example:
        - Monorepo with 5 projects
        - Using project-specific tags
        - Projects have dependencies on each other
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Output
      description: Please paste any relevant log output or error messages
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I am willing to submit a PR to fix this bug
          required: false
