name: Build and Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Unit Tests
      run: |
        echo "Running all unit tests including VersionResolutionTests..."
        dotnet test --no-build --configuration Release --verbosity normal
        if [ $? -ne 0 ]; then
          echo "❌ Unit tests failed! Build will not proceed."
          exit 1
        fi
        echo "✅ All unit tests passed!"

    - name: Run Version Resolution Regression Tests
      run: |
        echo "Running specific version resolution tests..."
        dotnet test --no-build --configuration Release --filter "FullyQualifiedName~VersionResolutionTests" --verbosity normal
        if [ $? -ne 0 ]; then
          echo "❌ Version resolution tests failed! Build will not proceed."
          exit 1
        fi
        echo "✅ Version resolution tests passed!"

    - name: Run Integration Tests
      uses: ./.github/actions/test-versioning-linux
      with:
        dotnet-version: '8.0.x'
    
    - name: Verify All Tests Passed
      run: |
        echo "✅ All tests passed successfully! Proceeding with packaging..."

    - name: Pack
      run: dotnet pack --no-restore --configuration Release --output ./nupkg

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate